language: node_js
node_js:
  - 8
before_script:
  - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/eleventy-base-blog/"
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: 432390aba832e81bb47b6b6e95698d1be29d7af0
  keep-history: true
  on:
    branch: master
